### ISSUE TITLE
Time-varying pump discharge pressure

### ISSUE THREAD

**Issue by dean-s-oliver** [equinor/ecalc#60]
I am interested in using eCalc for computation of GHG emissions given a schedule of well water injection rates and either BHP or WHP. It does not seem that eCalc currently accomodates time-varying pump discarge pressure, which would be needed for time varying BHP. Is there a plan to implement? Or is it there and I did not notice?
Dean Oliver 
NORCE

**Comment by olelod** [comment]
Hi Dean, thank you for your interest in eCalc.

Rate, suction pressure and discharge pressure can always be time-varying. They can be input as constant values, variables or expressions. Look at this simple example https://equinor.github.io/ecalc/docs/about/modelling/examples/simple/. You can add columns in the production_data.csv with suction and/or discharge pressure for a pump, with headers e.g. PUMP_PS or PUMP_PD, make new variables 

```
VARIABLES:
  pump_discharge_pressure:
    VALUE: SIM;PUMP_PD
```
and reference the new variable in the energy usage model for the pump:

```
         - NAME: Produced water reinjection pump
            CATEGORY: PUMP
            ENERGY_USAGE_MODEL:
              TYPE: PUMP
              CONDITION: $var.produced_water_reinjection_condition
              ENERGYFUNCTION: pump_chart
              RATE: $var.produced_water_reinjection_total_system_rate_m3_per_day
              FLUID_DENSITY: 1010
              SUCTION_PRESSURE: 10  # bara
              DISCHARGE_PRESSURE: $var.pump_discharge_pressure    # bara
```

Hope this answers you question.
